### ISSUE TITLE
"Terraform" package isn't showing up or installable when searching

### ISSUE THREAD

**Issue by aryounce** [SublimeText/Terraform#65]
This package isn't showing up in Package Control when invoked from inside Sublime Text, and the website shows the following warning:

![CleanShot 2024-08-11 at 13 02 53@2x](https://github.com/user-attachments/assets/ab70b8a3-fe5d-4365-8b4c-3998b24b3b44)

Since the `README` indicates that the project can be installed via Package Control I'm assuming this is not intentional.

**Comment by FichteFoll** [comment]
Oops, that was my bad. Fixed it in the channel and also added a proper tag for ST4 builds (which is the same as the currently released version).

**Comment by FichteFoll** [comment]
Also, thanks for the report. No idea when I would have noticed it but probably when I'd prepare the next version for ST4 only.
